---
title: "Report from comlandr FRED data pull"
output: html_document
params: 
  isEqual: NA
  rowNum: NA
  newRows: NA
  old: NA
  new: NA
  ggplot: NA
date: "`r Sys.time()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Summary

```{r datapull,echo=F,eval=T}
if (params$isEqual) {
  message("FRED data is unchanged")
} else {
  message("FRED data has changed")
  message(paste0("Number of rows in new pull = ",params$rowNum$new))
  message(paste0("Number of rows in current data = ",params$rowNum$old))
  
  if (params$newRows) {
    message("The difference is due to an ADDITION of NEW data")
  } else {
    message("The difference is unknown")
  }
  
  # Plots
  oldFred <- old |> 
    dplyr::mutate(source = "old")
  newFred <- new |> 
    dplyr::mutate(source = "new")
    dataF <- rbind(oldFred,newFred) |> 
      dplyr::mutate(date_var = lubridate::make_date(YEAR, MONTH))

  p <- ggplot2::ggplot(dataF) +
    ggplot2::geom_line(ggplot2::aes(x=date_var,y = value, color = source)) + 
    ggplot2::geom_point()
  
  p
}

```


## Links to repos:

* [comlandr](https://github.com/NOAA-EDAB/comlandr)
* [FRED](https://fred.stlouisfed.org/series/WPU0223)
