---
title: "Overview"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Overview}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


We will attempt to summarise the data sources, methods, assumptions made, and the caveats of note in the `comlandr` package.

## Data sources

Data are used from various sources to compile the resulting data pull

* Commercial landings are pulled from the Stock Efficiency Initiative (STOCKEFF). A product created and maintained by the NEFSC population dynamics branch.
* Herring data comes from the State of Maine. The data is updated periodically by the stock assessment scientist
* Catch by international (non US) vessels are reported to Northwest Atlantic Fisheries Organization [(NAFO)](https://www.nafo.int/). This data is pulled directly from their website.
* Observer data from the NEFSC is used to aid in the estimation of discards

### Commercial landings 

Commercial landings data resides in the Catch Accounting and Monitoring System [(CAMS)](https://www.greateratlantic.fisheries.noaa.gov/ro/fso/reports/cams/cams_documentation/) a database maintained by the Greater Atlantic Regional Fisheries Office [(GARFO)](https://www.fisheries.noaa.gov/about/greater-atlantic-regional-fisheries-office). This system was officially launched in 2022. Prior to this time landings data was more fragmented and "snapshots" of the data (housed at GARFO) was stored at the NEFSC. This was the source data for all stock assessments.

The Stock Efficiency Initiative was created (prior to the adoption of CAMS) with the goal of consolidating the landings data into a more digestible form for use in stock assessments (amongst many other things). STOCKEFF now incorporates CAMS data (post 2022) and legacy data to serve up a product for stock assessments.

`comlandr` uses the STOCKEFF product exclusively for all landings data.

The reason for this is to align the scientific products created by the Ecosystem Dynamics and Assessment Branch (EDAB) with stock assessments undertaken by Population Dynamics Branch by using the same underlying data source.

### Herring landings

Herring data comes from the State of Maine and is not fully integrated into CAMS (and therefore STOCKEFF). In `comlandr`, the Herring data is pulled from a separate source managed independently from STOCKEFF.

### Foreign landings

Landings by non US fishing vessels (foreign landings) within the Northwest Atlantic waters are managed by the Northwest Atlantic Fisheries Organization [(NAFO)](https://www.nafo.int/). `comlandr` pulls this data from the NAFO website and merges it with US landings data

For detailed information regarding NAFO data please review the `vignette("ForeignCatch")` and `vignette("ForeignCatchCompare21A21B")`

## Processing steps

## Discards

The reporting of discarding is not legally required. However estimates are required for management. `comlandr` uses 

## Caveats

* Although US landings data (SPPLIVLB) pulled from STOCKEFF can be retrieved from as early as 1964, species value (SPPVALUE) is only available from 1982. Prior to this date the value can not be reliably validated.

* Menhaden landings are not complete in the commercial database. 
