#' Assign landing records to an aggregated area
#'
#' Takes the output from \code{get_comland_data} and further aggregates from NAFO 
#' statistical areas to a user defined area.  Allows for species to be assigned by
#' proportions to more than two user defined areas from one stat area
#'
#'@param comland Data set generated by \code{get_comland_data}
#'@param userAreas Data frame. Definitions to aggregate statistical areas to user defined
#'                 areas
#'@param areaDescription Character. Name of column in userAreas that defines the new
#'                       area.
#'@param propDescription Character. Name of column in userAreas that defines the 
#'                       proportions of landings assigned to new area.
#'
#'@export

aggregate_gear <- function(comland, userGears, fleetDescription){
  
  #Pulling data
  message("Aggregating Gears ...")
  
  #Grab just the data
  comData <- copy(comland$comland)
  
  call <- dbutils::capture_function_call()
  
  #Convert userGears to data.table
  gears <- data.table::as.data.table(userGears)
  gears <- data.table::setnames(gears, fleetDescription, 'fleet')
  
  #Assign gears to fleets
  #Generate NEGEAR2 codes from NEGEAR
  if(is.numeric(comData$NEGEAR)){
    comData[NEGEAR < 100, NEGEAR3 := paste0(0, NEGEAR)]
    comData[NEGEAR >= 100, NEGEAR3 := NEGEAR]
    comData[, NEGEAR2 := as.numeric(substr(NEGEAR3, 1, 2))]
  } else {
    comData[, NEGEAR2 := as.numeric(substr(NEGEAR, 1, 2))]
  }
  
  fleets <- unique(gears$fleet)
  
  for(ifleet in 1:length(fleets)){
    fleet.gear <- gears[fleet == fleets[ifleet], NEGEAR2]
    fleet.mesh <- unique(gears[fleet == fleets[ifleet], MESHCAT])
    #Check if there is a mesh characteristic associated with this gear
    if(is.na(fleet.mesh)){
      comData[NEGEAR2 %in% fleet.gear, fleet := fleets[ifleet]]
    } else {
      comData[NEGEAR2 %in% fleet.gear & MESHCAT == fleet.mesh, fleet := fleets[ifleet]]
    }
  }
  
  comData[, fleet := as.factor(fleet)]
  
  #Drop extra columns and rename
  comData[, c('NEGEAR3', 'NEGEAR2', 'NEGEAR', 'MESHCAT') := NULL]
  data.table::setnames(comData, 'fleet', fleetDescription)
  
  #Aggregate over new gears
  #Aggregate to new areas
  catch.var <- names(comData)[which(!names(comData) %in% c('SPPLIVMT', 
                                                           'SPPVALUE'))]
  comData <- comData[, .(SPPLIVMT = sum(SPPLIVMT), SPPVALUE = sum(SPPVALUE)),
                       by = catch.var]
  
  #Add changes back into comland
  comland$comland <- comData[]
  comland$call <- c(comland$call, call)
  comland$userGears <- userGears
  
  return(comland[])
}                 
                 
