#' Assign landing records to an aggregated area
#'
#' Takes the output from \code{get_comland_data} and further aggregates from NAFO 
#' statistical areas to a user defined area.  Allows for species to be assigned by
#' proportions to more than two user defined areas from one stat area
#'
#'@param comland Data set generated by \code{get_comland_data}
#'@param userAreas Data frame. Definitions to aggregate statistical areas to user defined
#'                 areas
#'@param areaDescription Character. Name of column in userAreas that defines the new
#'                       area.
#'@param propDescription Character. Name of column in userAreas that defines the 
#'                       proportions of landings assigned to new area.
#'
#'@export

aggregate_area <- function(comland, userAreas, areaDescription, propDescription,
                           useForeign, applyPropValue = T){
  
  #Pulling data
  message("Aggregating Areas ...")
  
  #Grab just the data
  comData <- comland$comland
  
  call <- dbutils::capture_function_call()
  
  #Convert userAreas to data.table
  areas <- data.table::as.data.table(userAreas)
  data.table::setnames(areas, c(areaDescription, propDescription), c('newarea', 'prop'))
  
  #Figure out NAFO divisions/weightings
  if(useForeign){
    #Pull NAFO divisions
    NAFOAreas <- data.table::as.data.table(comlandr::get_areas(channel)$data)
    NAFOAreas <- unique(NAFOAreas[, c('AREA', 'NAFDVCD')])
    NAFOAreas <- NAFOAreas[, .(AREA = as.integer(AREA), 
                               NAFDVCD = as.integer(NAFDVCD))]
    areasNAFO <- merge(unique(areas[, c('AREA')]), NAFOAreas, by = 'AREA', all.x = T)
    
    #Calc area weights
    #Pull area of stat areas
    statarea <- sf::read_sf(dsn = system.file("extdata","Statistical_Areas_2010.shp",
                                              package="comlandr"), quiet = T)
    statarea.area <- data.table::data.table(AREA = statarea$Id,
                                            area = sf::st_area(statarea))
    areasNAFO <- merge(areasNAFO, statarea.area, by = 'AREA', all.x = T)
    
    #Get total per division
    areasNAFO[, divarea := sum(area), by = NAFDVCD]
    
    #Calculate strata weight
    areasNAFO[, weight := area / divarea]
    
    #Drop extra columns
    areasNAFO[, c('area', 'divarea') := NULL]
    
    #Calculate weighted proportions from Stat areas
    areas.weighted <- merge(areas, areasNAFO, by = 'AREA', all.x = T)
    div.prop <- areas.weighted[, .(prop = sum(prop * weight)), 
                               by = c('NESPP3', 'NAFDVCD', 'newarea')]
    
    #Get in the right format and merge
    data.table::setnames(div.prop, 'NAFDVCD', 'AREA')
    numberCols <- c('AREA', 'prop')
    div.prop[, (numberCols):= lapply(.SD, as.numeric), .SDcols = numberCols]
    areas <- data.table::rbindlist(list(areas, div.prop), use.names = T)
  }
  
  #Merge new area descriptions to landings
  new.area <- merge(comData, areas, by = c('NESPP3', 'AREA'), all.x = T, allow.cartesian=TRUE)
  
  #If no proportion assume 100% in
  new.area[is.na(prop), prop := 1]
  
  #Proportion landings to new areas
  new.area[, newspplivmt := SPPLIVMT * prop]
  if(applyPropValue) new.area[, newsppvalue := SPPVALUE * prop]
  
  #Drop extra columns and rename
  if(applyPropValue){
    new.area[, c('SPPLIVMT', 'SPPVALUE', 'prop') := NULL]
    data.table::setnames(new.area, c('newarea', 'newspplivmt', 'newsppvalue'), 
                         c(areaDescription, 'SPPLIVMT', 'SPPVALUE'))
  } else {
    new.area[, c('AREA', 'SPPLIVMT', 'prop') := NULL]
    data.table::setnames(new.area, c('newarea', 'newspplivmt'), 
                         c(areaDescription, 'SPPLIVMT'))
  }

  #Aggregate to new areas
  catch.var <- names(new.area)[which(!names(new.area) %in% c('SPPLIVMT', 
                                                             'SPPVALUE'))]
  new.area <- new.area[, .(SPPLIVMT = sum(SPPLIVMT), SPPLIVMT = sum(SPPVALUE)),
                       by = catch.var]
  
  #Add changes back into comland
   comland$comland <- new.area[]
   comland$call <- c(comland$call, call)
   comland$userAreas <- userAreas
  
  return(comland[])
}                 
