#' Assign landing records to an aggregated area
#'
#' Takes the output from \code{get_comland_data} and further aggregates from NAFO 
#' statistical areas to a user defined area.  Allows for species to be assigned by
#' proportions to more than two user defined areas from one stat area
#'
#'@param comland Data set generated by \code{get_comland_data}
#'@param userAreas Data frame. Definitions to aggregate statistical areas to user defined
#'                 areas
#'@param areaDescription Character. Name of column in userAreas that defines the new
#'                       area.
#'@param propDescription Character. Name of column in userAreas that defines the 
#'                       proportions of landings assigned to new area.
#'
#'@export

aggregate_area <- function(comData, userAreas, areaDescription, propDescription,
                           applyPropValue = T){
  
  call <- dbutils::capture_function_call()
  
  #Convert userAreas to data.table
  areas <- data.table::as.data.table(userAreas)
  setnames(areas, c(areaDescription, propDescription), c('newarea', 'prop'))
  
  #Merge new area descriptions to landings
  setnames(comData, areaDescription, 'newarea')
  new.area <- merge(comData, areas, by = c('NESPP3', 'newarea'), all.x = T)
  
  #If no proportion assume 100% in
  validAreas <- unique(areas[, newarea])
  new.area[is.na(prop) & newarea %in% validAreas, prop := 1]
  
  #drop records outside the scope
  new.area <- new.area[!is.na(prop), ]
  
  #Proportion landings to new areas
  new.area[, newspplivmt := SPPLIVMT * prop]
  if(applyPropValue) new.area[, newsppvalue := SPPVALUE * prop]
  
  #Drop extra columns and rename
  if(applyPropValue){
    new.area[, c('SPPLIVMT', 'SPPVALUE', 'prop') := NULL]
    data.table::setnames(new.area, c('newarea', 'newspplivmt', 'newsppvalue'), 
                         c(areaDescription, 'SPPLIVMT', 'SPPVALUE'))
  } else {
    new.area[, c('SPPLIVMT', 'prop') := NULL]
    data.table::setnames(new.area, c('newarea', 'newspplivmt'), 
                         c(areaDescription, 'SPPLIVMT'))
  }
  
  #Revert names in original dataset
  data.table::setnames(comData, 'newarea', areaDescription)
  
  #Add changes back into comland
  # comland$comland <- new.area.land[]
  # comland$call <- c(comland$call, call)
  # comland$userAreas <- userAreas
  
  return(new.area[])
}                 
