#' Assign landing records to an aggregated area
#'
#' Takes the output from \code{get_comland_data} and further aggregates from NAFO 
#' statistical areas to a user defined area.  Allows for species to be assigned by
#' proportions to more than two user defined areas from one stat area
#'
#'@param comland Data set generated by \code{get_comland_data}
#'@param userAreas Data frame. Definitions to aggregate statistical areas to user defined
#'                 areas
#'@param areaDescription Character. Name of column in userAreas that defines the new
#'                       area.
#'@param propDescription Character. Name of column in userAreas that defines the 
#'                       proportions of landings assigned to new area.
#'
#'@export

assign_area <- function(comland, userAreas, areaDescription, propDescription){
  
  call <- dbutils::capture_function_call()
  
  #Pull out landings from comland object
  landings <- comland$comland
  
  #Convert userAreas to data.table
  areas <- data.table::as.data.table(userAreas)
  setnames(areas, c(areaDescription, propDescription), c('newarea', 'prop'))
  
  #Merge new area descriptions to landings
  new.area.land <- merge(landings, areas, by = c('NESPP3', 'AREA'))
  
  #Proportion landings to new areas
  new.area.land[, newspplivmt := SPPLIVMT * prop]
  new.area.land[, newsppvalue := SPPVALUE * prop]
  
  #Drop extra columns
  new.area.land[, c('AREA', 'SPPLIVMT', 'SPPVALUE', 'prop') := NULL]
  
  #Rename columns
  data.table::setnames(new.area.land, c('newarea', 'newspplivmt', 'newsppvalue'), 
                       c(areaDescription, 'SPPLIVMT', 'SPPVALUE'))
  
  #Add changes back into comland
  comland$comland <- new.area.land[]
  comland$call <- c(comland$call, call)
  comland$userAreas <- userAreas
  
  return(comland)
}                 
